CentreonAutoDiscovery\Domain\Credential\Credential:
  properties:
    id:
      type: int
      groups:
        - 'credential_main'
    name:
      type: string
      groups:
        - 'credential_main'
    typeId:
      type: int
      groups:
        - 'credential_main'
    parameters:
      type: "array<CentreonAutoDiscovery\\Domain\\Credential\\CredentialParameter>"
      groups:
        - 'param_main'