CentreonAutoDiscovery\Domain\Credential\CredentialParameter:
  access_type: public_method
  properties:
    value:
      type: string
      groups:
        - 'param_main'
    isPassword:
      accessor:
        getter: isPassword
        setter: setPassword
      type: boolean
      groups:
        - 'param_main'