CentreonAutoDiscovery\Domain\Job\DiscoveryJob:
  virtual_properties:
    scheduling:
      since_version: 2.1
      groups: [job_main]
      exp: object.preserializeScheduling()
  properties:
    id:
      type: integer
      groups: [job_main]
    alias:
      type: string
      groups: [job_main]
    credentialId:
      type: integer
      groups: [job_main]
    providerId:
      type: integer
      groups: [job_main]
    creationDate:
      type: DateTime
      groups: [job_main]
    last_execution:
      since_version: 2.1
      type: DateTime
      groups: [job_main]
    status:
      type: integer
      groups: [job_main]
    duration:
      type: integer
      groups: [job_main]
    executionMode:
      since_version: 2.1
      type: integer
      groups: [job_main]
    analysisMode:
      since_version: 2.1
      type: integer
      groups: [job_main]
    numberOfHostsDiscovered:
      type: integer
      groups: [job_main]
    message:
      type: string
      groups: [job_main]
    proxy:
      type: Centreon\Domain\Proxy\Proxy
      groups: [proxy_main]
    monitoringServerId:
      type: integer
      groups: [job_main]
    jobParameters:
      type: array<CentreonAutoDiscovery\Domain\Job\JobParameter>
      groups: [param_main]
    mappersToApply:
      type: array<CentreonAutoDiscovery\Domain\Mapper\Mapper\AbstractMapper>
      groups: [mapper_main]
