CentreonAutoDiscovery\Domain\Mapper\Mapper\AbstractMapper:
  exclusion_policy: ALL
  custom_accessor_order: [order, type, source, destination, conditions]
  discriminator:
    field_name: type
    disabled: false
    groups: [mapper_main]
  properties:
    order:
      type: integer
      groups: [mapper_main]
    source:
      type: string
      groups: [mapper_main]
    destination:
      type: string
      groups: [mapper_main]
    conditions:
      type: array<CentreonAutoDiscovery\Domain\Mapper\Mapper\MapperCondition>
      groups: [mapper_main]
    mapperType:
      expose: false