CentreonAutoDiscovery\Domain\Mapper\HostModificationResult:
  properties:
    host:
      type: "Centreon\\Domain\\HostConfiguration\\Host"
      groups: [mapper_result]
    discoveredHostId:
      serialized_name: id
      type: integer
      groups: [mapper_with_discovered_id]
    errorMessages:
      type: array
      groups: [mapper_result]
