CentreonAutoDiscovery\Domain\Mapper\Mapper\MapperCondition:
  properties:
    source:
      type: string
      groups: [mapper_main]
    value:
      groups: [mapper_main]
    operator:
      type: string
      groups: [mapper_main]