CentreonAutoDiscovery\Domain\Provider\Provider:
  properties:
    id:
      type: integer
      groups: [provider_main, provider_min]
    pluginPackId:
      type: integer
      groups: [provider_main]
    name:
      type: string
      groups: [provider_main, provider_min]
    description:
      type: string
      groups: [provider_main]
    icon:
      type: string
      groups: [provider_main]
    type:
      type: 'CentreonAutoDiscovery\Domain\Provider\ProviderType'
      groups: [provider_type_main]
    isNeedProxy:
      type: boolean
      groups: [provider_main, provider_min]
    jobParametersTemplate:
      type: array<CentreonAutoDiscovery\Domain\Job\JobParameter>
      groups: [provider_main_with_param]
    hostTemplateId:
      type: integer
      groups: [provider_main]
    mappersExamples:
      type: array
      groups: [provider_main]